### PR TITLE
feat: includes the item's thumbnails in PackedItem

### PR DESCRIPTION
**Pull request by ReidyT**

### CODE REVIEW

**Review by spaenleh — APPROVED** [review]
So you will provide always all thumbnail sizes ?

**Comment by ReidyT** [comment]
You raise a good point, at the moment I'm only returning medium and small, but the type doesn't reflect that... maybe I should actually return all the sizes? if not, it could be a headache to know which route returns PackedItems of which size.

what do you think? @spaenleh @pyphilia @Defferrard

**Comment by Defferrard** [comment]
> You raise a good point, at the moment I'm only returning medium and small, but the type doesn't reflect that... maybe I should actually return all the sizes? if not, it could be a headache to know which route returns PackedItems of which size.
> 
> what do you think? @spaenleh @pyphilia @Defferrard

I'm not sure if I've understood it properly, but could be simply return `small` by default, and if the frontend needs a different size, it asks in the querystring ?

**Comment by ReidyT** [comment]
> > You raise a good point, at the moment I'm only returning medium and small, but the type doesn't reflect that... maybe I should actually return all the sizes? if not, it could be a headache to know which route returns PackedItems of which size.
> > what do you think? @spaenleh @pyphilia @Defferrard
> 
> I'm not sure if I've understood it properly, but could be simply return `small` by default, and if the frontend needs a different size, it asks in the querystring ?

I think it is not a bad idea, but it will add unnecessary complexity in my sense. Indeed, you'll have to know the queryParam to determine the available sizes vs knowing you always have access to x sizes (like small and medium) for example.

**Comment by Defferrard** [comment]
> > > You raise a good point, at the moment I'm only returning medium and small, but the type doesn't reflect that... maybe I should actually return all the sizes? if not, it could be a headache to know which route returns PackedItems of which size.
> > > what do you think? @spaenleh @pyphilia @Defferrard
> > 
> > 
> > I'm not sure if I've understood it properly, but could be simply return `small` by default, and if the frontend needs a different size, it asks in the querystring ?
> 
> I think it is not a bad idea, but it will add unnecessary complexity in my sense. Indeed, you'll have to know the queryParam to determine the available sizes vs knowing you always have access to x sizes (like small and medium) for example.

Otherwise, all thumbnails URL should be the same. If you need a different size, you should add a `?size=medium` in the `img` brackets. But I'm don't know if it is possible to with s3.

**Review by Defferrard — APPROVED** [review]
Without considering the last comments, it looks good to me ! Well done ! 🚀

**Comment by ReidyT** [comment]
> > > > You raise a good point, at the moment I'm only returning medium and small, but the type doesn't reflect that... maybe I should actually return all the sizes? if not, it could be a headache to know which route returns PackedItems of which size.
> > > > what do you think? @spaenleh @pyphilia @Defferrard
> > > 
> > > 
> > > I'm not sure if I've understood it properly, but could be simply return `small` by default, and if the frontend needs a different size, it asks in the querystring ?
> > 
> > 
> > I think it is not a bad idea, but it will add unnecessary complexity in my sense. Indeed, you'll have to know the queryParam to determine the available sizes vs knowing you always have access to x sizes (like small and medium) for example.
> 
> Otherwise, all thumbnails URL should be the same. If you need a different size, you should add a `?size=medium` in the `img` brackets. But I'm don't know if it is possible to with s3.

Not sure, but I don't think it's possible actually, because we are using signed urls. But yeah, ideally it could be the best solution I think...

**Pull request merged**
